// FaqSection.jsx
import React, { useMemo } from "react";

const faqs = [
  // Column 1
  [
    {
      q: "Do you offer flexible plans?",
      a: "Yes. 3-month, 6-month, and annual subscriptions are available, plus a trial.",
    },
    {
      q: "What does SEBI registration mean?",
      a: "It ensures regulatory compliance, not guaranteed profit.",
    },
    {
      q: "Do you offer refunds?",
      a: "No refunds are provided; fees cover research efforts only.",
    },
  ],
  // Column 2
  [
    {
      q: "Are returns guaranteed?",
      a: "No. While research is thorough, market results cannot be assured.",
    },
    {
      q: "How much capital should I start with?",
      a: "There’s no fixed minimum, but risk management is advised.",
    },
  ],
  // Column 3
  [
    {
      q: "Who handles research?",
      a: "All calls are generated by a certified SEBI-registered research analyst.",
    },
    {
      q: "Can I share tips with others?",
      a: "No. Subscriptions are for individual use only.",
    },
  ],
];

function QA({ q, a }) {
  return (
    <div className="py-4">
      <h4 className="text-[25px] sm:text-[20px] font-extrabold text-gray-900">
        {q}
      </h4>
      <p className="mt-2 text-[16px] font-semibold sm:text-[16px] leading-[1.9] text-gray-600">
        {a}
      </p>
    </div>
  );
}

export default function FaqSection() {
  const normalized = useMemo(() => {
    const maxLen = Math.max(...faqs.map((col) => col.length));
    return faqs.map((col) => {
      const clone = [...col];
      while (clone.length < maxLen) clone.push({ q: "", a: "" }); 
      return clone;
    });
  }, []);

  return (
    <section id="faq" className="relative overflow-hidden">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-0 -z-10 top-0 h-[280px]
                   bg-[radial-gradient(ellipse_at_top,rgba(0,0,0,0.05),transparent_60%)]"
      />

      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16">
        <div className="mb-8 sm:mb-10">
          <h2 className="text-[28px] sm:text-[32px] md:text-[40px] font-black text-gray-900">
            FAQ
          </h2>
          <span className="mt-2 block h-[3px] w-10 bg-sky-600 rounded-sm" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-0">
          {normalized.map((col, i) => (
            <div key={i} className="divide-y divide-gray-200">
              {col.map((item, idx) =>
                item.q ? (
                  <QA key={idx} {...item} />
                ) : (
                  <div key={idx} className="py-4 invisible">
                    <QA q="" a="" />
                  </div>
                )
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
